# escape=`

# renovate: datasource=github-releases depName=watchtower packageName=nicholas-fedor/watchtower
ARG WATCHTOWER_VERSION=1.12.2

FROM mcr.microsoft.com/windows/nanoserver:ltsc2025@sha256:88a45eb14a45c111131ce1464d0e3b5ae545e3c0ea8dcbe9cf0b8c60c848f08a AS build

ARG WATCHTOWER_VERSION
RUN `
  mkdir tmp && mkdir bin`
	&& curl -sSfLo tmp/file.zip https://github.com/nicholas-fedor/watchtower/releases/download/v%WATCHTOWER_VERSION%/watchtower_windows_amd64_%WATCHTOWER_VERSION%.zip `
  && tar -C c:\bin -oxzf tmp/file.zip watchtower.exe`
  && /bin/watchtower --help

FROM mcr.microsoft.com/windows/nanoserver:1809@sha256:64ad7c4349a8673f00c7306c22c6f1a4f08e0a5b8e2ef164deb2cafb8d5e2d2f

USER ContainerAdministrator

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" `
  org.opencontainers.image.authors="Michael Kriese <michael.kriese@visualon.de>" `
  org.opencontainers.image.licenses="MIT" `
  org.opencontainers.image.source="https://github.com/visualon/docker-watchtower" `
  org.opencontainers.image.url="https://watchtower.nickfedor.com"

LABEL com.centurylinklabs.watchtower="true"

ENTRYPOINT ["/bin/watchtower"]

ENV DOCKER_HOST=npipe:////./pipe/docker_engine

ARG WATCHTOWER_VERSION
LABEL org.opencontainers.image.version="${WATCHTOWER_VERSION}"

COPY --from=build /bin /bin

HEALTHCHECK CMD ["/bin/watchtower", "--health-check"]
