# escape=`

# renovate: datasource=github-releases depName=watchtower packageName=nicholas-fedor/watchtower
ARG WATCHTOWER_VERSION=1.19.0

FROM mcr.microsoft.com/windows/nanoserver:ltsc2025@sha256:fda578d34f56de2f60d91a178fd954fdc95596ebb67b3bc363deb708ef1fd94c AS build

ARG WATCHTOWER_VERSION
RUN `
  mkdir tmp && mkdir bin`
	&& curl -sSfLo tmp/file.zip https://github.com/nicholas-fedor/watchtower/releases/download/v%WATCHTOWER_VERSION%/watchtower_windows_amd64_%WATCHTOWER_VERSION%.zip `
  && tar -C c:\bin -oxzf tmp/file.zip watchtower.exe`
  && /bin/watchtower --help

FROM mcr.microsoft.com/windows/nanoserver:ltsc2025@sha256:fda578d34f56de2f60d91a178fd954fdc95596ebb67b3bc363deb708ef1fd94c

USER ContainerAdministrator

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" `
  org.opencontainers.image.authors="Michael Kriese <michael.kriese@visualon.de>" `
  org.opencontainers.image.licenses="MIT" `
  org.opencontainers.image.source="https://github.com/visualon/docker-watchtower" `
  org.opencontainers.image.url="https://watchtower.nickfedor.com"

LABEL com.centurylinklabs.watchtower="true"

ENTRYPOINT ["/bin/watchtower"]

ENV DOCKER_HOST=npipe:////./pipe/docker_engine

ARG WATCHTOWER_VERSION
LABEL org.opencontainers.image.version="${WATCHTOWER_VERSION}"

COPY --from=build /bin /bin

HEALTHCHECK CMD ["/bin/watchtower", "--health-check"]
