name: build

on:
  push:

env:
  OWNER: ${{ github.repository_owner }}
  FILE: watchtower
  IMAGE: ghcr.io/${{ github.repository_owner }}/watchtower
  BUILDKIT_PROGRESS: plain
  BUILDX_NO_DEFAULT_ATTESTATIONS: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  windows:
    runs-on: windows-2025

    timeout-minutes: 60

    strategy:
      matrix:
        os:
        - 2019
        - 2022
        - 2025

    env:
      BASE: ${{ matrix.os }}
      TAG: windows-${{ matrix.os }}

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Init
        run: ./bin/init.sh
        shell: bash

      # ignore not yet existing images
      - name: Fetch the docker images
        run: |
          docker pull ${{ env.IMAGE }}
          docker pull ${{ env.IMAGE }}:${{ env.TAG }}
          docker pull ${{ env.IMAGE }}:${{ env.VERSION }}-${{ env.TAG }}
        continue-on-error: true

      - name: Build the docker image
        run: |
          docker build \
            -t ${{ env.IMAGE }}:${{ env.TAG }} \
            -t ${{ env.IMAGE }}:${{ env.VERSION }}-${{ env.TAG }} \
            --cache-from ${{ env.IMAGE }} \
            --cache-from ${{ env.IMAGE }}:${{ env.TAG }} \
            --cache-from ${{ env.IMAGE }}:${{ env.VERSION }}-${{ env.TAG }} \
            -f Dockerfile.${{ env.BASE }} \
            .
        working-directory: ./windows
        shell: bash

      - name: Test run
        # 2019 isn't compatible
        if: matrix.os != 2019
        run:  docker compose --file docker-compose.test.yml run sut
        working-directory: ./windows
        env:
          IMAGE: ${{ env.IMAGE }}:${{ env.TAG }}

      - name: Log into registry
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Publish the docker images
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ env.IMAGE }}:${{ env.TAG }}
          docker push ${{ env.IMAGE }}:${{ env.VERSION }}-${{ env.TAG }}

  linux:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    env:
      TAG: linux-amd64

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Init
        run: ./bin/init.sh
        shell: bash

      - name: docker-config
        uses: containerbase/internal-tools@01c5c8dd57e355f4e15450c781e36992dc602a5e # v3.13.17
        with:
          command: docker-config

      - name: Build the Docker image
        run: docker buildx bake test

      - name: Test run
        run: docker compose --file docker-compose.test.yml run sut
        working-directory: ./linux
        env:
          IMAGE: ${{ env.IMAGE }}:${{ env.TAG }}

      - name: Log into registry
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Publish the Docker image
        if: github.ref == 'refs/heads/main'
        run: docker buildx bake build

  multi-arch:
    needs: [linux, windows]

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: docker-config
        uses: containerbase/internal-tools@01c5c8dd57e355f4e15450c781e36992dc602a5e # v3.13.17
        with:
          command: docker-config

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Init
        run: ./bin/init.sh

      - name: Build the Docker multiarch manifest
        run: |
          docker manifest create ${{ env.IMAGE }} \
            ${{ env.IMAGE }}:linux-amd64 \
            ${{ env.IMAGE }}:windows-2019 \
            ${{ env.IMAGE }}:windows-2022 \
            ${{ env.IMAGE }}:windows-2025
          docker manifest create ${{ env.IMAGE }}:${{ env.VERSION }} \
            ${{ env.IMAGE }}:${{ env.VERSION }}-linux-amd64 \
            ${{ env.IMAGE }}:${{ env.VERSION }}-windows-2019 \
            ${{ env.IMAGE }}:${{ env.VERSION }}-windows-2022 \
            ${{ env.IMAGE }}:${{ env.VERSION }}-windows-2025

      - name: Publish the Docker multiarch manifest
        run: |
          docker manifest push ${{ env.IMAGE }}
          docker manifest push ${{ env.IMAGE }}:${{ env.VERSION }}

      - name: Inspect the Docker multiarch manifest
        run: docker manifest inspect ${{ env.IMAGE }}

  release:
    needs: multi-arch

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Init
        run: ./bin/init.sh

      - uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          allowUpdates: true
          body: See https://github.com/containrrr/watchtower/releases/tag/v${{ env.VERSION }} for more changes
          commit: ${{ github.sha }}
          name: ${{ env.VERSION }}
          tag: v${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
